language: python
script: "./build.sh"
branches:
  only:
  - release/1.0.0

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35

install:
  - pip install -e ".[dev,test, docs, release]"
  - pip install tox coveralls

script: tox

after_success:
  - coveralls
