language: python

branches:
  only:
  - release/1.0.0

matrix:
  include:
  - os: linux
    python: 2.7
    env: TOXENV=py27
  - os: linux
    python: 3.3
    env: TOXENV=py33
  - os: linux
    python: 3.4
    env: TOXENV=py34
  - os: linux
    python: 3.5
    env: TOXENV=py35

install:
  - pip install -e ".[dev,test, docs, release]"
  - pip install tox coveralls

script: tox

after_success:
  - "./scripts/build.sh"
  - coveralls

env:
  global:
    secure: cMHxps7vVXxR2HRrtAMDb+D+ikzRNIXRo8g4yxBoHfcFYKi4s0rfJB3I8oDpru/COFYJXu0UBp3OtZJOuNKWLkjuqBRz1NI/oxJZ/KK3a8Az5PWZDvMKmbBblJ8x3PRcywDa/DQu5joD9rzygJEVyQH7BeXETRBorQ2nMN4n4iGFKZ0ZkJjiAm3E0OsC+pbUVvlZYV1TjZ6z/4zENE/5zZLBGdXMeyeZgZg4xijnENPKrCgAIbR1kYsRS+HErV7xXjDD2szKQXaimlUNV/BGzdbPaq1Hbdg+7ytAN0pFB57tJyp53yXuhTV3YgdTnAt605fUAr6oaxMkG6okoDK8MmrvcZfQ2wj7aQ+kE5rreNAcuCh+6XEouVCBlkRpd5F8+y0PIA6/LRVlt7QG8iPvWCeSheVmBj1DrtOFib27zYFIy6PLQW84VX/+J5iu0DZKCeo9EEhlk8416kLRipvlNaFUquihczOXtvEfRbC48nv/H4sgoH/iSpe/xQhLYopJooASkYlIPojBHf03ARyufXuYC4EtK6cFEkQ0y9knM1PIBgPp00FFgTWZmgH4jBQQOrGIkg1/o5Qp/XV5NPQEhGVElrmpgNmyHqtD7CiiV9PhNiIJk8qElYOmcXusPmtAJEz5nmjAN1VHM3IvCWGUHXuX4q/FXiyr+445FusEwEo=
