# Site settings

# Build settings
#ghlighter: rouge
#markdown: kramdown
#kramdown:
#        input: GFM
#        auto_ids: true
#        syntax_highlighter: rouge


markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
